version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ahish2006/devops-frontend:latest
    container_name: devops-frontend
    ports:
      - "80:80"
    restart: unless-stopped
